### ISSUE TITLE
CI runs on simulated merge commit, but leaves comments on unmerged code

### ISSUE THREAD

**Issue by ethan-lowman-dd** [theupdateframework/go-tuf#241] opened 2022-03-27 00:19 UTC
CI appears to run on a simulated merge commit, such as [this one](https://github.com/theupdateframework/go-tuf/commit/8220751deb9c76d1bab02300cd7c4bbf84de5292) for [this PR](https://github.com/theupdateframework/go-tuf/pull/175). This is useful, since it verifies that the build will remain green upon merge, but it results in confusing test output and PR comments from GitHub actions, such as the following. These errors do not correspond with the code around the comments on the PR, but rather the code in the simulated merge commit.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/53835328/160261269-7a28ca30-f91e-4ab3-aba9-7f6739f1c048.png">

**Comment by trishankatdatadog** [comment] 2022-03-27 10:25
Yeah, I was confused, too. How do we fix this?

**Comment by ethan-lowman-dd** [comment] 2022-03-27 17:53
One way would be to run tests on the branch itself (not a merge commit) but set up a [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/using-a-merge-queue) to re-run CI on the simulated merge commit before merge completes.

**Comment by joshuagl** [comment] 2022-03-28 08:47
@rdimitrov do you think you could take a look at this?

**Comment by joshuagl** [comment] 2022-03-29 10:12
@ethan-lowman-dd can you help us reproduce the results in your screenshot? The PR and merge commit you linked to don't show any Check failures here as we haven't merged the CI changes yet.

**Comment by ethan-lowman-dd** [comment] 2022-03-30 20:10
Here is the CI run that failed: https://github.com/theupdateframework/go-tuf/actions/runs/2046098449

**Comment by rdimitrov** [comment] 2024-01-31 21:15
Closing since the code base changed and so it is no longer relevant

Thanks for raising this 👍

**Closed by rdimitrov** 2024-01-31 21:15 UTC
