### ISSUE TITLE
go 1.19 action is using go 1.17 to run tests

### ISSUE THREAD

**Issue by naveensrinivasan** [theupdateframework/go-tuf#372] opened 2022-09-04 20:20 UTC
The go1.19 action is using go 1.17 to run tests. 

![image](https://user-images.githubusercontent.com/172697/188331940-390741cb-5c5d-44b6-b0eb-b1eaf1f22e38.png)

https://github.com/theupdateframework/go-tuf/runs/8053810526?check_suite_focus=true

**Comment by znewman01** [comment] 2022-09-04 22:01
IIUC this is a duplicate of https://github.com/theupdateframework/go-tuf/issues/362 

CC @ethan-lowman-dd

**Comment by mnm678** [comment] 2022-09-29 17:31
@ethan-lowman-dd @trishankatdatadog @znewman01 Can we mark this as closed by #364?

**Closed** 2022-09-29 18:02 UTC
