### ISSUE TITLE
cleanup: Initialize new root and targets at version 1

### ISSUE THREAD

**Issue by asraa** [theupdateframework/go-tuf#272] opened 2022-04-19 16:30 UTC
Currently, the API for `NewRoot()` and `NewTargets()` initialized version at 0, whereas they should generally be started at 1. 

Clean this up, and existing tests.
https://github.com/theupdateframework/go-tuf/pull/175/files#r850775514

**Comment by abs007** [comment] 2022-09-28 13:13
Hi, it seems that the spec versions are already initialized to 1 in `types.go`

**Comment by asraa** [comment] 2022-09-28 20:32
> Hi, it seems that the spec versions are already initialized to 1 in types.go

Hey! It's not spec version, but the version of the metadata file.

**Comment by abs007** [comment] 2022-09-29 08:34
Could you point me to the file where the metadata version is specified? I've also looked at `repo.go` and there seems to be a version getting assigned in line 125 and 130 though I'm not sure if its the metadata version.

**Comment by znewman01** [comment] 2022-09-29 11:21
See context here: https://github.com/theupdateframework/go-tuf/pull/175/files#r850775514

Those lines you've pointed out *do* set the root/targets to 1! This issue is meant to track moving that over to `NewTargets` and `NewRoot` into data.go.

For instance, look at `NewRoot`: https://github.com/theupdateframework/go-tuf/blob/4f55897602eacf9fc202b8a7f25236d21bfc800a/data/types.go#L120-L129

It doesn't set `Version`, which means that it gets set to the default `int64` value of `0`.

The fix for this issue is easy: just set `Version` to `1` in `NewRoot` (data.go) and `NewTargets`, and *remove* the lines that you found it repo.go. The hard part is that a lot of existing tests break when you do that 🙂 So you have to fix those too.

**Comment by abs007** [comment] 2022-09-29 17:31
Oh, gotcha. The review comment wasn't loading for me earlier. Thanks for the explanation!

**Comment by abs007** [comment] 2022-10-02 12:17
> Currently, the version is incremented the first time the metadata is staged to the local store. 

Could I get some more info as to where exactly does the `version` get incremented automatically?

Asking this as tests check to see if the version results to 1. With me adding `Version: 1` in `NewRoot()` and `NewTargets()`, the extra incrementation takes the `Version` to `2`. Hence I'm confused between dealing with the incrementation or checking for a result of `2` instead.

**Comment by rdimitrov** [comment] 2022-10-05 12:19
@abs007 - Sure, here are a few tips, but do check out the rest of the code too 👍 
* https://github.com/theupdateframework/go-tuf/blob/b4b954d5250b438b244ebaeed5fab56fec8f06b0/repo.go#L125
* https://github.com/theupdateframework/go-tuf/blob/b4b954d5250b438b244ebaeed5fab56fec8f06b0/repo.go#L236
* https://github.com/theupdateframework/go-tuf/blob/b4b954d5250b438b244ebaeed5fab56fec8f06b0/repo.go#L461
* https://github.com/theupdateframework/go-tuf/blob/b4b954d5250b438b244ebaeed5fab56fec8f06b0/repo.go#L572

**Comment by abs007** [comment] 2022-10-07 14:43
@ethan-lowman-dd  I'm attempting to solve this issue and I have set Version to 1 for NewRoot() and NewTargets(). So now I'm wondering if I should remove the code lines that increment the version during staging since Version has a value of 1 by default now. Would appreciate your feedback on this.

**Comment by ethan-lowman-dd** [comment] 2022-10-07 15:19
@abs007 The relevant code is in `repo.go`, searching for `FileIsStaged`, `Version++`, and `Version =`. We cant remove the `Version` increment completely, since it still needs to be incremented somehow when updates are staged. I would first update the `NewRoot()` and `NewTargets()` to initialize `Version` to 1, and then focus on getting the existing unit tests to pass. If I remember correctly, the issue is that if you initialize `Version` to 1 in `NewRoot()` and `NewTargets()`, this metadata is not staged in the local store, so when something like this runs:
```
	if !r.local.FileIsStaged("root.json") {
		root.Version++
	}
```
The `root.json` is incremented to 2, skipping version 1. I would see if it's maybe possible to stage metadata right after where `NewRoot()` and `NewTargets()` are called in `repo.go`.

**Comment by abs007** [comment] 2022-10-07 19:12
@ethan-lowman-dd  So from what I could understand, in the functions where
```go
	if !r.local.FileIsStaged("root.json") {
		root.Version++
	}
```
is present, the `root()` method is being called (which returns a pointer to the `data.Root` struct) prior to the code block. `root()` now checks to see if any metadata for `"root.json"` exists. If it doesn't, then the `NewRoot()` func is called to return a newly initialized root, else, the json data is unmarshaled and fed to a `Root` type which is then returned. So, staging metadata after `NewRoot()` doesn't seem possible since `root()` would always have to run prior to this block. 

Since, `Version` needs to be incremented whenever the metadata isn't staged, we can check for 2 in the tests instead. I thought of having `if !r.local.FileIsStaged("root.json") && root.Version == 0 {}` but this doesn't make much sense as Version is going to default to 1 now.

**Comment by abs007** [comment] 2022-10-17 13:00
Hi, I'd like a final go-ahead to push a pr with the suggested changes. Thanks.

**Comment by znewman01** [comment] 2022-10-17 13:31
Go ahead!

**Comment by abs007** [comment] 2022-10-18 17:56
It seems that the `role1.json` file also gets it's metadata version bumped up when checking in line [2087](https://github.com/theupdateframework/go-tuf/blob/master/repo_test.go#L2087). Target or root json files getting their version bumped up makes sense because of the change but why is is happening to the `role1.json` file too? Any context would help, thanks.

**Comment by abs007** [comment] 2022-10-22 16:51
Is [this](https://github.com/theupdateframework/go-tuf/blob/master/repo_test.go#L2389) line supposed to exist?

**Comment by rdimitrov** [comment] 2024-01-31 21:19
Closing since the code base changed and this is already fixed in the new implementation.

Thanks for raising this 👍

**Closed by rdimitrov** 2024-01-31 21:19 UTC
Labels: bug, help wanted, good first issue
